name: virtual_private_network
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # for splash screen
  animated_splash_screen: ^1.3.0

  # for drawing svg
  flutter_svg: ^1.1.6

  # for routing
  go_router: ^5.2.0

  # for easier creating launcher icon
  flutter_launcher_icons: ^0.11.0

  # for internet speed test
  speed_test_dart: ^1.0.4+1

  # for state management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  # for speed animation
  syncfusion_flutter_gauges: ^20.3.58

  # for vpn realization
  openvpn_flutter: ^1.2.2

  # for http requests
  http: ^0.13.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

#  build_runner: ^2.1.7
#  injectable_generator: ^2.0.1

  flutter_lints: ^2.0.0

# flutter_launcher_icons - Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/launcher_icon.png"
  image_path_android: "assets/images/launcher_icon.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "assets/images/launcher_icon.png"
  adaptive_icon_foreground: "assets/images/launcher_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/flags/
    - assets/images/powOn.svg
    - assets/images/stop.svg
    - assets/images/map.svg
